[package]
name = "instrumentrs-core"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Core library for instrumentRs."
readme = "README.md"

[dependencies]
thiserror = { workspace = true }
