[workspace]
members = [
  "examples/digoutbox",
  "crates/instrumentrs",
  "crates/instrumentrs-core",
  "crates/instrumentrs-macros",
  "tests/derive-macro-tests",
  "crates/instrumentrs-core",
]
resolver = "3"

package.version = "0.2.0"
package.authors = ["Reto Trappitsch <reto@galactic-forensics.space>"]
package.license = "MIT OR Apache-2.0"
package.homepage = "https://instrument.rs"
package.repository = "https://github.com/trappitsch/instrumentrs"
package.edition = "2024"
package.rust-version = "1.97"

[workspace.dependencies]
instrumentrs = { path = "./crates/instrumentrs", version = "=0.2.0" }
instrumentrs-core = { path = "./crates/instrumentrs-core", version = "=0.2.0" }
instrumentrs-macros = { path = "./crates/instrumentrs-macros/", version = "=0.2.0" }

proc-macro2 = "1"
quote = "1"
syn = "3"
termcolor = "1.4"
thiserror = "2"

trybuild = "1"
